apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: devsecops-prod
  labels:
    app: app-backend-app
    team: team-devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-backend-app
  template:
    metadata:
      labels:
        app: app-backend-app
        team: team-devsecops
    spec:
      serviceAccountName: backendapp-service-account
      imagePullSecrets:
      - name: ghcr-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: backend-app
        image: ghcr.io/Meriem1601/ctama-js-backend-app:staging
        ports:
        - containerPort: 3000
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        volumeMounts:
        - name: app-storage
          mountPath: /usr/src/app
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: backend-app-pvc
