apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: devsecops-prod
  labels:  # Added labels here
    team: team-devsecops
    app: app-mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql  # This must match the template labels
      team: team-devsecops  # Added this to match the template labels
  template:
    metadata:
      labels:
        app: mysql  # This must match the selector
        team: team-devsecops  # Added this to ensure it matches the selector
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.36
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password  # This should match the key in your Secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:  # Added resource requests and limits
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:  # Set privileged to false
          privileged: false  # Ensures the container does not run in privileged mode
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
