apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
  namespace: devsecops-prod
spec:
  selector:
    app: backend-app  # Match the app label in the deployment
  ports:
    - protocol: TCP
      port: 3000  # Port that the service exposes inside the cluster
      targetPort: 3000  # Port on the backend-app container
      nodePort: 30001  # Optional: specify the NodePort (range is 30000-32767)
  type: NodePort  # Use NodePort since LoadBalancer isn't available
