apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: devsecops-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-management-role
  namespace: devsecops-prod
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "pods/log", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-management-rolebinding
  namespace: devsecops-prod
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: devsecops-prod
roleRef:
  kind: Role
  name: app-management-role
  apiGroup: rbac.authorization.k8s.io
