apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-app-pv
  namespace: devsecops-prod
spec:
  capacity:
    storage: 5Gi  # Adjust as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/backend-app  # Local storage path on your nodes

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-app-pvc
  namespace: devsecops-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Match the storage size of the PersistentVolume
