apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: devsecops-prod
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None  # This makes the service headless, which is useful for StatefulSets
