apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-app-pv
  namespace: devsecops-prod
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/backend-app  

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-app-pvc
  namespace: devsecops-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
