---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsecops-deployer
  namespace: devsecops-prod

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devsecops-prod
  name: devsecops-deployer-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devsecops-deployer-rolebinding
  namespace: devsecops-prod
subjects:
- kind: ServiceAccount
  name: devsecops-deployer
  namespace: devsecops-prod
roleRef:
  kind: Role
  name: devsecops-deployer-role
  apiGroup: rbac.authorization.k8s.io
